# Generated by Django 2.1.7 on 2019-03-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='priority',
        ),
    ]
