# Generated by Django 2.1.7 on 2019-04-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='issue',
            name='hours_required',
            field=models.IntegerField(default=0),
        ),
    ]
