# Generated by Django 2.1.7 on 2019-04-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservoted',
            old_name='post',
            new_name='bug',
        ),
        migrations.RenameField(
            model_name='uservoted',
            old_name='user',
            new_name='bug_voter',
        ),
        migrations.RenameField(
            model_name='uservotedfeature',
            old_name='post',
            new_name='feature',
        ),
        migrations.RenameField(
            model_name='uservotedfeature',
            old_name='user',
            new_name='feature_voter',
        ),
    ]
