# Generated by Django 2.1.7 on 2019-04-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='author',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='userseenissue',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userseenissue',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uservoted',
            name='post',
        ),
        migrations.RemoveField(
            model_name='uservoted',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='UserSeenIssue',
        ),
        migrations.DeleteModel(
            name='UserVoted',
        ),
    ]
