# Generated by Django 2.1.7 on 2019-03-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='genre',
            field=models.CharField(choices=[('Navigation', 'Navigation'), ('Flight Controls', 'Flight Controls'), ('Auto Pilot', 'Auto Pilot'), ('None', 'None')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issue_tracker.Issue'),
        ),
    ]
