# Generated by Django 2.1.7 on 2019-04-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='min_hours',
            field=models.IntegerField(default=2),
        ),
    ]
