# Generated by Django 2.1.7 on 2019-04-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_auto_20190417_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservoted',
            old_name='bug_voter',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='uservotedfeature',
            old_name='feature_voter',
            new_name='user',
        ),
    ]
