# Generated by Django 2.1.7 on 2019-04-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_featureorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureorders',
            name='author',
        ),
        migrations.AddField(
            model_name='issue',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='purchased',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='FeatureOrders',
        ),
    ]
