# Generated by Django 2.1.7 on 2019-04-03 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue_tracker', '0002_auto_20190402_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSeenIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_tracker.Issue')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='seen_issue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
