# Generated by Django 2.1.7 on 2019-03-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_remove_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('BUG', 'Bug'), ('FEATURE ', 'Feature')], default='Bug', max_length=10),
        ),
    ]
