# Generated by Django 2.1.7 on 2019-04-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_auto_20190410_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cost_hrs',
            field=models.IntegerField(choices=[(6, 'Navigation'), (8, 'Flight Controls'), (5, 'Auto Pilot'), (0, 'None')], default=0),
        ),
    ]
