# Generated by Django 2.1.7 on 2019-04-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_auto_20190417_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservoted',
            old_name='bug',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='uservotedfeature',
            old_name='feature',
            new_name='post',
        ),
    ]
