# Generated by Django 2.1.7 on 2019-04-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_issue_cost_hrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='cost_hrs',
            field=models.IntegerField(choices=[('Navigation', 6), ('Flight Controls', 8), ('Auto Pilot', 5), ('None', 0)], default=0),
        ),
    ]
