# Generated by Django 2.1.7 on 2019-04-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0005_auto_20190410_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='cost_hrs',
        ),
    ]
