# Generated by Django 2.1.7 on 2019-04-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0006_remove_issue_cost_hrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='genre',
            field=models.CharField(choices=[('NAV', 'Navigation'), ('CON', 'Flight Controls'), ('AUT', 'Auto Pilot'), ('NON', 'None')], default='None', max_length=30),
        ),
    ]
