# Generated by Django 2.1.7 on 2019-04-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0007_auto_20190410_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='genre',
            field=models.CharField(choices=[('Navigation', 'Navigation'), ('Flight Controls', 'Flight Controls'), ('Auto Pilot', 'Auto Pilot'), ('None', 'None')], default='None', max_length=30),
        ),
    ]
