# Generated by Django 2.1.7 on 2019-04-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0008_auto_20190410_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='genre',
            field=models.CharField(choices=[('Navigation', 'Navigation'), ('Flight Controls', 'Flight Controls'), ('Auto Pilot', 'Auto Pilot')], default='None', max_length=30),
        ),
    ]
