# Generated by Django 2.1.7 on 2019-04-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0010_auto_20190410_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='genre',
            field=models.CharField(choices=[('Navigation', 'Navigation'), ('Flight Controls', 'Flight Controls'), ('Auto Pilot', 'Auto Pilot')], default='Navigation', max_length=30, null=True),
        ),
    ]
