version: "3.1"

services:
  app:
    build: .
    image: ddeveloper72/django-app:v0
    command: "python manage.py runserver 0.0.0.0:8000"
   
    volumes:
      - .:/app_dir
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: drone-app
    env_file:
      - ./.env
    environment:
      - USE_DOCKER=yes

  db:
    image: mysql:8.0
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
    container_name: drone-db
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-drone_db}
      - MYSQL_USER=${MYSQL_USER:-drone_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-drone_password}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    container_name: drone-adminer
