version: "3.1"
services:
  app:
    image: my_django_app:v0.1
    build: ./app_dir
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app_dir
      # - ./docker/secrets:/run/secrets
    env_file:
      - ./.env    
    environment:
      - USE_DOCKER=yes
    deploy:
      replicas: 2

  db:
    image: mysql:latest
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    restart: always

  adminer:
    image: adminer
    restart: always
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
