# Generated by Django 4.2.16 on 2026-05-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_alter_userprofile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Public name shown on your posts (defaults to username if not set)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_location",
            field=models.BooleanField(
                default=False,
                help_text="Make your location visible on your public profile",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Tell others about yourself (visible on your public profile)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(
                blank=True, help_text="Private - never shown publicly", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Optional - only shown if you enable 'Show location on profile'",
                max_length=30,
            ),
        ),
    ]
