"""
Django settings for drone_debug project.
Generated by 'django-admin startproject' using Django 2.1.7.
For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import environ

# Initialise environment variables (updated to match Movie Rater approach)
env = environ.Env(
    # Set default values
    DEBUG=(bool, True),
    SECRET_KEY=(str, 'django-insecure-default-key-please-change-in-production'),
)

# Read .env file explicitly
env_file = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '.env')
if os.path.exists(env_file):
    environ.Env.read_env(env_file)
    print(f"Loading environment from: {env_file}")
else:
    print("No .env file found")

import dj_database_url
from django.contrib.messages import constants as messages

# Toggle DEBUG via environment, default to True for local development
DEBUG = env.bool("DEBUG", default=True)
print("Running in development mode" if DEBUG else "Running in production mode")

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = [
    '.localhost',
    '127.0.0.1',
    '.herokuapp.com',
    'ddeveloper72-custom-drone.herokuapp.com'
]

# CSRF and Security Settings for Heroku
CSRF_TRUSTED_ORIGINS = [
    'https://ddeveloper72-custom-drone.herokuapp.com',
    'https://*.herokuapp.com',
]

# Tell Django to trust X-Forwarded-Proto header from Heroku
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'bootstrap4',
    'landing_page',
    'issue_tracker',
    'accounts',
    'blog',
    'cart',
    'checkout',
    'search',
    'storages',
    'userprofile',
]


MIDDLEWARE = [
    'drone_debug.middleware.DatabaseHealthCheckMiddleware',  # Health check endpoint
    'drone_debug.middleware.DatabaseRetryMiddleware',  # Retry database connections
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'drone_debug.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'cart.contexts.cart_contents'
            ],
        },
    },
]

WSGI_APPLICATION = 'drone_debug.wsgi.application'

AUTH_PROFILE_MODULE = 'userprofile.UserProfile'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# Database configuration with priority order: Azure SQL > DATABASE_URL > MySQL
# Check Azure SQL first (for production on Heroku)
if env('AZURE_SQL_HOST', default=None):
    # Azure SQL Server configuration for production
    azure_sql_host = env('AZURE_SQL_HOST')
    azure_schema = env('AZURE_SQL_SCHEMA', default='drone_app_v2')
    
    DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': env('AZURE_SQL_NAME'),
            'USER': env('AZURE_SQL_USER'),
            'PASSWORD': env('AZURE_SQL_PASSWORD'),
            'HOST': azure_sql_host,
            'PORT': env('AZURE_SQL_PORT', default='1433'),
            'CONN_MAX_AGE': 300,  # Keep connections alive for 5 minutes
            'CONN_HEALTH_CHECKS': True,  # Test connection before each request
            'OPTIONS': {
                'driver': 'ODBC Driver 18 for SQL Server',
                'extra_params': f'Encrypt=yes;TrustServerCertificate=no;Connection Timeout=120;Login Timeout=120;',
                'host_is_server': True,
            },
        }
    }
    print(f"Azure SQL Server configuration found. Using Azure SQL Server: {env('AZURE_SQL_NAME')} on {azure_sql_host}")
    print(f"Using schema: {azure_schema}")
elif env('DATABASE_URL', default=None):
    # Parse DATABASE_URL (fallback for local development or other platforms)
    database_url = env('DATABASE_URL')
    DATABASES = {
        'default': dj_database_url.parse(database_url)
    }
    # Add connection management settings
    DATABASES['default']['CONN_MAX_AGE'] = 300
    DATABASES['default']['CONN_HEALTH_CHECKS'] = True
    
    # Determine database type from URL
    if database_url.startswith('postgres'):
        print("Database URL found. Using PostgreSQL")
    elif database_url.startswith('mysql'):
        print("Database URL found. Using MySQL")
        # Use mysql.connector (pure Python) instead of mysqlclient (requires C compilation)
        DATABASES['default']['ENGINE'] = 'mysql.connector.django'
    else:
        print(f"Database URL found. Using database from: {database_url.split(':')[0]}")
else:
    # Check if MySQL credentials are available
    if env('MYSQL_DATABASE', default=None):
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': env('MYSQL_DATABASE'),
                'USER': env('MYSQL_USER'),
                'PASSWORD': env('MYSQL_ROOT_PASSWORD'),
                'HOST': env('MYSQL_HOST'),
                'PORT': env('MYSQL_PORT'),
                'CONN_MAX_AGE': 300,
                'CONN_HEALTH_CHECKS': True,
            }
        }
        print("Using MySQL for local development")
    else:
        # Fallback to SQLite for local development (no setup required)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
        print("No database configuration found. Using SQLite for local development")


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 4,
        }
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'accounts.backends.EmailAuth'
]


MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

AWS_S3_OBJECT_PARAMETERS = {
    'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
    'CacheControl': 'max-age=94608000',
}

AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default='custom-drone')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='eu-west-1')
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")

# AWS bucket name, 'custom-drone', gets injected here
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

AWS_DEFAULT_ACL = None

STATICFILES_LOCATION = 'static'
# STATICFILES_STORAGE = 'custom_storages.StaticStorage'  # Disabled - serving from container
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  # WhiteNoise for production

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

MEDIAFILES_LOCATION = 'media'
DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'  # S3 storage for media files (images, uploads)


MEDIA_ROOT = (
    os.path.join(BASE_DIR, 'media'),
)

# AWS custom domain and , media files location, gets injected here
MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

STRIPE_PUBLISHABLE = env('STRIPE_PUBLISHABLE')
STRIPE_SECRET = env('STRIPE_SECRET')

# Email Configuration
# Option 1: SendGrid (Recommended for production - no 2FA required)
if env('SENDGRID_API_KEY', default=None):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.sendgrid.net'
    EMAIL_HOST_USER = 'apikey'  # This is literal 'apikey', not your actual key
    EMAIL_HOST_PASSWORD = env('SENDGRID_API_KEY')
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    DEFAULT_FROM_EMAIL = env("EMAIL_ADDRESS")
    SERVER_EMAIL = env("EMAIL_ADDRESS")
    print("Using SendGrid for email delivery")

# Option 2: Gmail (Requires 2FA + App Password)
elif env('EMAIL_PASSWORD', default=None):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_HOST_USER = env("EMAIL_ADDRESS")
    EMAIL_HOST_PASSWORD = env("EMAIL_PASSWORD")
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    DEFAULT_FROM_EMAIL = env("EMAIL_ADDRESS")
    SERVER_EMAIL = env("EMAIL_ADDRESS")
    print("Using Gmail for email delivery")

# Option 3: Console backend for development (emails print to console)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@customdrone.com'
    print("Using console email backend - emails will print to terminal")

# Password reset timeout (1 hour for security)
PASSWORD_RESET_TIMEOUT = 3600
